### ISSUE TITLE
 那个数量你的只有加减,我现在换成EditText手动输入,但是点击EditText的时候软键盘弹出来后又关闭了

### ISSUE THREAD

**Issue by wildma** [zilianliuxue/TBShoppingCart#3]
大神, 那个数量你的只有加减,我现在换成EditText手动输入,但是点击EditText的时候软键盘弹出来后又关闭了. 怎么解决呢?

**Comment by zilianliuxue** [comment]
你的问题，我昨天把代码重新改了一下，把编辑数量的地方改了下，一种方案是在原地编辑修复了强制关闭软键盘的bug,我还做了一个模仿jd的方案，也就是弹出dialog修改

**Comment by wildma** [comment]
真给力. 这么快就解决了!

**Comment by morning7** [comment]
getGroupView里的notifyDataChagne去掉就可以了
